name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-ap:
    runs-on: ubuntu-latest

  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'coretto'
          java-version: '17'

      - name: Run Tests
        run: mvn -B test --file pom.xml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: |
          mvn clean
          mvn -B package --file pom.xml

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest
